id: git_basics_add
hints:
- Use git branch to create a new branch and git checkout to switch branches
- Use git add to add files and git commit to commit those changes
startFlow:
  do:
  - actionId: bot_message
    params:
      person: head-of-rd
      messages:
      - text: "Awesome. The tutorial continues! 🥁 now you can start making some changes to our codebase."
        delay: 1500
      - text: "The first thing I need you to do is **add a `CODEOWNERS` file** that we are missing in our repository."
        delay: 2500
      - text: "This file lets everyone know who is responsible for the code and who should be reviewing changes. Here it is: https://wilco-engine.herokuapp.com/quests/git_basics/CODEOWNERS"
        delay: 2700
      - text: "Please create **a new branch** and **add the file to the root directory** in the repository you just cloned. Then **commit the change** and **push it** to GitHub."
        delay: 4000
      - text: "Also, feel free to consult GitHub’s [documentation](https://docs.github.com/) on how to do this."
        delay: 2000
trigger:
  type: github_push
  flowNode:
    if:
      conditions:
      - conditionId: github_is_file_added_in_push
        params:
          defaultResult: false
          fileName:
          - CODEOWNERS
      then:
        do:
        - actionId: bot_message
          params:
            person: head-of-rd
            messages:
              - text: "Perfect execution! Well done."
              delay: 1500
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: head-of-rd
            messages:
            - text: "Hmm, I see you pushed some changes to a new branch, but it seems **you forgot to add the `CODEOWNERS` file** I sent you. Could you please add it to the repo, commit, and **push it to Github**?"
              delay: 2500